#!/bin/sh
# Generated for Agar by BSDBuild 3.2.
# <http://bsdbuild.hypertriton.com>

prefix="/mingw64"
exec_prefix="/mingw64"
exec_prefix_set="no"
libdir="/mingw64/lib"

usage="Usage: agar-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs]"

if test $# -eq 0; then
	echo "${usage}" 1>&2
	exit 1
fi

while test $# -gt 0; do
	case "$1" in
	-*=*)
		optarg=`echo "$1" | LC_ALL="C" sed 's/[-_a-zA-Z0-9]*=//'`
		;;
	*)
		optarg=
		;;
	esac

	case $1 in
	--prefix=*)
		prefix=$optarg
		if test $exec_prefix_set = no ; then
			exec_prefix=$optarg
		fi
		;;
	--prefix)
		echo "$prefix"
		;;
	--exec-prefix=*)
		exec_prefix=$optarg
		exec_prefix_set=yes
		;;
	--exec-prefix)
		echo "$exec_prefix"
		;;
	--version)
		echo "1.5.0"
		;;
	--cflags)
		echo "-I/mingw64/include/agar -I/mingw64/include/SDL -D_GNU_SOURCE=1  -I/mingw64/include/freetype2 -mms-bitfields -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include -IC:/msys64/mingw64/include       -I/mingw64/include/libpng16        "
		;;
	--libs | --static-libs)
		echo "-L/mingw64/lib -lag_gui -lag_core -L/mingw64/lib -lSDL.dll -L/mingw64/lib -lfreetype -LC:/msys64/mingw64/lib -lfontconfig -lfreetype  -L/mingw64/lib -lopengl32 -lgdi32    -lm -L/mingw64/lib -ljpeg -L/mingw64/lib -lpng16 -lpthread     -lwinmm  "
		;;
	*)
		echo "${usage}" 1>&2
		exit 1
		;;
	esac
	shift
done
