hdefs["ENABLE_NLS"] = nil
mdefs["ENABLE_NLS"] = "no"
mdefs["HAVE_GETTEXT"] = "no"
hdefs["PREFIX"] = "/usr/local"
hdefs["LOCALEDIR"] = "/locale"
hdefs["MANDIR"] = "/usr/local/man"
hdefs["SHAREDIR"] = "/usr/local/share"
hdefs["DATADIR"] = "/usr/local/share"
hdefs["LIBDIR"] = "/usr/local/lib"
hdefs["SBINDIR"] = "/usr/local/sbin"
hdefs["INFODIR"] = "/usr/local/share/info"
hdefs["SYSCONFDIR"] = "/usr/local/etc"
hdefs["BINDIR"] = "/usr/local/bin"
hdefs["LIBEXECDIR"] = "/usr/local/libexec"
hdefs["LOCALSTATEDIR"] = "/usr/local/var"
mdefs["PACKAGE"] = "Agar"
hdefs["PACKAGE"] = "Agar"
mdefs["VERSION"] = "1.4.1"
hdefs["VERSION"] = "1.4.1"
mdefs["RELEASE"] = "Landscapes of Frozen Methane"
hdefs["RELEASE"] = "Landscapes of Frozen Methane"
mdefs["SHAREDIR"] = "${PREFIX}/share/agar"
hdefs["SHAREDIR"] = "/usr/local/share/agar"
mdefs["LOCALEDIR"] = "${PREFIX}/share/agar/locale"
hdefs["LOCALEDIR"] = "/usr/local/share/agar/locale"
mdefs["TTFDIR"] = "${PREFIX}/share/agar/fonts"
hdefs["TTFDIR"] = "/usr/local/share/agar/fonts"
mdefs["INCLDIR"] = "${PREFIX}/include/agar"
hdefs["INCLDIR"] = "/usr/local/include/agar"
mdefs["EXECSUFFIX"] = ".exe"
hdefs["EXECSUFFIX"] = ".exe"
mdefs["HAVE_CC_WARNINGS"] = "yes"
hdefs["HAVE_CC_WARNINGS"] = "yes"
mdefs["HAVE_GCC"] = "yes"
hdefs["HAVE_GCC"] = "yes"
mdefs["HAVE_IEEE754"] = "no"
hdefs["HAVE_IEEE754"] = nil
mdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
hdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
mdefs["HAVE_BOUNDED_ATTRIBUTE"] = "no"
hdefs["HAVE_BOUNDED_ATTRIBUTE"] = nil
mdefs["HAVE_CONST_ATTRIBUTE"] = "yes"
hdefs["HAVE_CONST_ATTRIBUTE"] = "yes"
mdefs["HAVE_DEPRECATED_ATTRIBUTE"] = "yes"
hdefs["HAVE_DEPRECATED_ATTRIBUTE"] = "yes"
mdefs["HAVE_FORMAT_ATTRIBUTE"] = "yes"
hdefs["HAVE_FORMAT_ATTRIBUTE"] = "yes"
mdefs["HAVE_NONNULL_ATTRIBUTE"] = "yes"
hdefs["HAVE_NONNULL_ATTRIBUTE"] = "yes"
mdefs["HAVE_NORETURN_ATTRIBUTE"] = "yes"
hdefs["HAVE_NORETURN_ATTRIBUTE"] = "yes"
mdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
hdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
mdefs["HAVE_PURE_ATTRIBUTE"] = "yes"
hdefs["HAVE_PURE_ATTRIBUTE"] = "yes"
mdefs["HAVE_WARN_UNUSED_RESULT_ATTRIBUTE"] = "yes"
hdefs["HAVE_WARN_UNUSED_RESULT_ATTRIBUTE"] = "yes"
hdefs["HAVE_LONG_DOUBLE"] = nil
hdefs["HAVE_LONG_LONG"] = nil
mdefs["HAVE_CYGWIN"] = "no"
hdefs["HAVE_CYGWIN"] = nil
mdefs["CC"] = "/mingw/bin/cc"
mdefs["CFLAGS"] = ""
mdefs["_MK_HAVE_SYS_TYPES_H"] = "yes"
hdefs["_MK_HAVE_SYS_TYPES_H"] = "yes"
mdefs["HAVE_64BIT"] = "no"
hdefs["HAVE_64BIT"] = nil
mdefs["_MK_HAVE_UNSIGNED_TYPEDEFS"] = "no"
hdefs["_MK_HAVE_UNSIGNED_TYPEDEFS"] = nil
mdefs["_MK_HAVE_STDLIB_H"] = "yes"
hdefs["_MK_HAVE_STDLIB_H"] = "yes"
mdefs["_MK_HAVE_UNISTD_H"] = "no"
hdefs["_MK_HAVE_UNISTD_H"] = nil
mdefs["_MK_HAVE_LIMITS_H"] = "no"
hdefs["_MK_HAVE_LIMITS_H"] = nil
mdefs["_MK_HAVE_FLOAT_H"] = "yes"
hdefs["_MK_HAVE_FLOAT_H"] = "yes"
hdefs["HAVE_PROGNAME"] = nil
mdefs["HAVE_MATH"] = "yes"
hdefs["HAVE_MATH"] = "yes"
mdefs["MATH_CFLAGS"] = ""
hdefs["MATH_CFLAGS"] = ""
mdefs["MATH_LIBS"] = "-lm"
hdefs["MATH_LIBS"] = "-lm"
mdefs["HAVE_MATH_C99"] = "yes"
hdefs["HAVE_MATH_C99"] = "yes"
mdefs["MATH_C99_CFLAGS"] = ""
hdefs["MATH_C99_CFLAGS"] = ""
mdefs["MATH_C99_LIBS"] = "-lm"
hdefs["MATH_C99_LIBS"] = "-lm"
hdefs["HAVE_GETPWUID"] = nil
hdefs["HAVE_GETUID"] = nil
hdefs["HAVE_STRSEP"] = nil
hdefs["HAVE_SNPRINTF"] = "yes"
hdefs["HAVE_VSNPRINTF"] = "yes"
mdefs["HAVE_VASPRINTF"] = "no"
hdefs["HAVE_VASPRINTF"] = nil
hdefs["_MK_HAVE_SIGNAL"] = "yes"
hdefs["_MK_HAVE_SETJMP"] = "yes"
hdefs["_MK_HAVE_STRTOLL"] = nil
hdefs["_MK_HAVE_STRTOLD"] = nil
hdefs["_MK_LITTLE_ENDIAN"] = "yes"
hdefs["_MK_BIG_ENDIAN"] = nil
hdefs["HAVE_DLFCN_H"] = nil
hdefs["HAVE_DLOPEN"] = nil
mdefs["HAVE_DLOPEN"] = "no"
hdefs["HAVE_DLOPEN"] = nil
mdefs["DSO_CFLAGS"] = ""
hdefs["DSO_CFLAGS"] = ""
mdefs["DSO_LIBS"] = ""
hdefs["DSO_LIBS"] = ""
hdefs["HAVE_MACH_O_DYLD_H"] = nil
hdefs["HAVE_DYLD"] = nil
hdefs["HAVE_DYLD_RETURN_ON_ERROR"] = nil
mdefs["DSO_CFLAGS"] = ""
hdefs["DSO_CFLAGS"] = ""
mdefs["DSO_LIBS"] = ""
hdefs["DSO_LIBS"] = ""
hdefs["HAVE_DL_H"] = nil
mdefs["HAVE_SHL_LOAD"] = "no"
hdefs["HAVE_SHL_LOAD"] = nil
hdefs["HAVE_SHL_LOAD"] = nil
hdefs["HAVE_GETTIMEOFDAY"] = nil
hdefs["HAVE_SELECT"] = nil
hdefs["HAVE_SETPROCTITLE"] = nil
hdefs["HAVE_SYSLOG"] = nil
hdefs["HAVE_SYSLOG_R"] = nil
hdefs["HAVE_VSYSLOG"] = nil
hdefs["HAVE_VSYSLOG_R"] = nil
hdefs["HAVE_GLOB"] = nil
hdefs["HAVE_GETOPT"] = nil
hdefs["HAVE_EXECVP"] = nil
mdefs["HAVE_CLOCK_GETTIME"] = "no"
hdefs["HAVE_CLOCK_GETTIME"] = nil
mdefs["HAVE_CLOCK_GETTIME"] = "no"
hdefs["HAVE_CLOCK_GETTIME"] = nil
hdefs["HAVE_CLOCK_GETTIME"] = nil
mdefs["HAVE_CLOCK_WIN32"] = "no"
hdefs["HAVE_CLOCK_WIN32"] = nil
hdefs["HAVE_CLOCK_WIN32"] = nil
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE"
mdefs["WNO_UNINITIALIZED"] = ""
hdefs["AG_DEBUG"] = nil
hdefs["AG_OBJDEBUG"] = nil
hdefs["AG_LEGACY"] = "yes"
hdefs["ENABLE_GUI"] = "yes"
mdefs["SUBDIR_gui"] = "gui"
mdefs["HAVE_SDL"] = "yes"
hdefs["HAVE_SDL"] = "yes"
mdefs["SDL_CFLAGS"] = "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main"
hdefs["SDL_CFLAGS"] = "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main"
mdefs["SDL_LIBS"] = "-L/usr/local/lib -lmingw32 -lSDLmain -lSDL -mwindows"
hdefs["SDL_LIBS"] = "-L/usr/local/lib -lmingw32 -lSDLmain -lSDL -mwindows"
mdefs["HAVE_LIBOPENGL32"] = "yes"
hdefs["HAVE_LIBOPENGL32"] = "yes"
mdefs["HAVE_OPENGL"] = "yes"
hdefs["HAVE_OPENGL"] = "yes"
mdefs["OPENGL_CFLAGS"] = ""
hdefs["OPENGL_CFLAGS"] = ""
mdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32"
hdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32"
mdefs["SDL_CFLAGS"] = "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main "
mdefs["HAVE_X11"] = "no"
hdefs["HAVE_X11"] = nil
hdefs["X11_CFLAGS"] = nil
hdefs["X11_LIBS"] = nil
hdefs["HAVE_X11"] = nil
mdefs["HAVE_GLX"] = "no"
hdefs["HAVE_GLX"] = nil
hdefs["GLX_CFLAGS"] = nil
hdefs["GLX_LIBS"] = nil
hdefs["HAVE_GLX"] = nil
mdefs["HAVE_WGL"] = "yes"
hdefs["HAVE_WGL"] = "yes"
mdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32 -lgdi32"
hdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32 -lgdi32"
mdefs["HAVE_FREETYPE"] = "yes"
hdefs["HAVE_FREETYPE"] = "yes"
mdefs["FREETYPE_CFLAGS"] = "-I/usr/local/include/freetype2 -I/usr/local/include"
hdefs["FREETYPE_CFLAGS"] = "-I/usr/local/include/freetype2 -I/usr/local/include"
mdefs["FREETYPE_LIBS"] = "-L/usr/local/lib -lfreetype"
hdefs["FREETYPE_LIBS"] = "-L/usr/local/lib -lfreetype"
hdefs["HAVE_JPEG"] = nil
hdefs["JPEG_CFLAGS"] = nil
hdefs["JPEG_LIBS"] = nil
hdefs["HAVE_JPEG"] = nil
hdefs["HAVE_PNG"] = nil
hdefs["PNG_CFLAGS"] = nil
hdefs["PNG_LIBS"] = nil
hdefs["HAVE_LIBPNG14"] = nil
hdefs["HAVE_PNG"] = nil
hdefs["AG_NETWORK"] = nil
hdefs["HAVE_GETADDRINFO"] = nil
hdefs["HAVE_DB4"] = nil
mdefs["DB4_CFLAGS"] = ""
mdefs["DB4_LIBS"] = ""
mdefs["HAVE_PTHREADS"] = "yes"
hdefs["HAVE_PTHREADS"] = "yes"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE "
mdefs["PTHREADS_CFLAGS"] = ""
mdefs["PTHREADS_LIBS"] = "-lpthread"
hdefs["PTHREADS_CFLAGS"] = ""
hdefs["PTHREADS_LIBS"] = "-lpthread"
mdefs["HAVE_PTHREADS_XOPEN"] = "yes"
hdefs["HAVE_PTHREADS_XOPEN"] = "yes"
mdefs["PTHREADS_XOPEN_CFLAGS"] = "-U_XOPEN_SOURCE -D_XOPEN_SOURCE=600"
mdefs["PTHREADS_XOPEN_LIBS"] = "-lpthread"
hdefs["HAVE_PTHREADS_XOPEN"] = "yes"
hdefs["PTHREADS_XOPEN_CFLAGS"] = "-U_XOPEN_SOURCE -D_XOPEN_SOURCE=600"
hdefs["PTHREADS_XOPEN_LIBS"] = "-lpthread"
mdefs["HAVE_PTHREAD_MUTEX_RECURSIVE"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE"] = "yes"
mdefs["HAVE_PTHREAD_MUTEX_RECURSIVE_NP"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE_NP"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE_NP"] = "yes"
hdefs["AG_THREADS"] = "yes"
hdefs["ASTRONOMICAL_UNITS"] = nil
hdefs["HISTORICAL_UNITS"] = "yes"
hdefs["ENABLE_MATH"] = "yes"
mdefs["SUBDIR_math"] = "math"
hdefs["HAVE_SSE"] = nil
hdefs["HAVE_SSE2"] = nil
hdefs["HAVE_SSE3"] = nil
hdefs["INLINE_SSE"] = nil
hdefs["INLINE_SSE2"] = nil
hdefs["INLINE_SSE3"] = nil
hdefs["HAVE_ALTIVEC"] = nil
hdefs["HAVE_ALTIVEC_H"] = nil
hdefs["INLINE_ALTIVEC"] = nil
hdefs["SINGLE_PRECISION"] = nil
hdefs["DOUBLE_PRECISION"] = "yes"
hdefs["QUAD_PRECISION"] = nil
hdefs["ENABLE_VG"] = "yes"
mdefs["SUBDIR_vg"] = "vg"
hdefs["ENABLE_RG"] = "yes"
mdefs["SUBDIR_rg"] = "rg"
hdefs["ENABLE_DEV"] = "yes"
mdefs["SUBDIR_dev"] = "dev"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE  -I/h/AgarCompilation/agar-1.4.1/include"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE -I/h/AgarCompilation/agar-1.4.1/include"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE  -I/h/AgarCompilation/agar-1.4.1/include -I/h/AgarCompilation/agar-1.4.1/include/agar"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE -I/h/AgarCompilation/agar-1.4.1/include -I/h/AgarCompilation/agar-1.4.1/include/agar"
hdefs["ENABLE_NLS"] = nil
mdefs["ENABLE_NLS"] = "no"
mdefs["HAVE_GETTEXT"] = "no"
hdefs["PREFIX"] = "/usr/local"
hdefs["LOCALEDIR"] = "/locale"
hdefs["MANDIR"] = "/usr/local/man"
hdefs["SHAREDIR"] = "/usr/local/share"
hdefs["DATADIR"] = "/usr/local/share"
hdefs["LIBDIR"] = "/usr/local/lib"
hdefs["SBINDIR"] = "/usr/local/sbin"
hdefs["INFODIR"] = "/usr/local/share/info"
hdefs["SYSCONFDIR"] = "/usr/local/etc"
hdefs["BINDIR"] = "/usr/local/bin"
hdefs["LIBEXECDIR"] = "/usr/local/libexec"
hdefs["LOCALSTATEDIR"] = "/usr/local/var"
mdefs["PACKAGE"] = "Agar"
hdefs["PACKAGE"] = "Agar"
mdefs["VERSION"] = "1.4.1"
hdefs["VERSION"] = "1.4.1"
mdefs["RELEASE"] = "Landscapes of Frozen Methane"
hdefs["RELEASE"] = "Landscapes of Frozen Methane"
mdefs["SHAREDIR"] = "${PREFIX}/share/agar"
hdefs["SHAREDIR"] = "/usr/local/share/agar"
mdefs["LOCALEDIR"] = "${PREFIX}/share/agar/locale"
hdefs["LOCALEDIR"] = "/usr/local/share/agar/locale"
mdefs["TTFDIR"] = "${PREFIX}/share/agar/fonts"
hdefs["TTFDIR"] = "/usr/local/share/agar/fonts"
mdefs["INCLDIR"] = "${PREFIX}/include/agar"
hdefs["INCLDIR"] = "/usr/local/include/agar"
mdefs["EXECSUFFIX"] = ".exe"
hdefs["EXECSUFFIX"] = ".exe"
mdefs["HAVE_CC_WARNINGS"] = "yes"
hdefs["HAVE_CC_WARNINGS"] = "yes"
mdefs["HAVE_GCC"] = "yes"
hdefs["HAVE_GCC"] = "yes"
mdefs["HAVE_IEEE754"] = "no"
hdefs["HAVE_IEEE754"] = nil
mdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
hdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
mdefs["HAVE_BOUNDED_ATTRIBUTE"] = "no"
hdefs["HAVE_BOUNDED_ATTRIBUTE"] = nil
mdefs["HAVE_CONST_ATTRIBUTE"] = "yes"
hdefs["HAVE_CONST_ATTRIBUTE"] = "yes"
mdefs["HAVE_DEPRECATED_ATTRIBUTE"] = "yes"
hdefs["HAVE_DEPRECATED_ATTRIBUTE"] = "yes"
mdefs["HAVE_FORMAT_ATTRIBUTE"] = "yes"
hdefs["HAVE_FORMAT_ATTRIBUTE"] = "yes"
mdefs["HAVE_NONNULL_ATTRIBUTE"] = "yes"
hdefs["HAVE_NONNULL_ATTRIBUTE"] = "yes"
mdefs["HAVE_NORETURN_ATTRIBUTE"] = "yes"
hdefs["HAVE_NORETURN_ATTRIBUTE"] = "yes"
mdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
hdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
mdefs["HAVE_PURE_ATTRIBUTE"] = "yes"
hdefs["HAVE_PURE_ATTRIBUTE"] = "yes"
mdefs["HAVE_WARN_UNUSED_RESULT_ATTRIBUTE"] = "yes"
hdefs["HAVE_WARN_UNUSED_RESULT_ATTRIBUTE"] = "yes"
hdefs["HAVE_LONG_DOUBLE"] = nil
hdefs["HAVE_LONG_LONG"] = nil
mdefs["HAVE_CYGWIN"] = "no"
hdefs["HAVE_CYGWIN"] = nil
mdefs["CC"] = "/mingw/bin/cc"
mdefs["CFLAGS"] = ""
mdefs["_MK_HAVE_SYS_TYPES_H"] = "yes"
hdefs["_MK_HAVE_SYS_TYPES_H"] = "yes"
mdefs["HAVE_64BIT"] = "no"
hdefs["HAVE_64BIT"] = nil
mdefs["_MK_HAVE_UNSIGNED_TYPEDEFS"] = "no"
hdefs["_MK_HAVE_UNSIGNED_TYPEDEFS"] = nil
mdefs["_MK_HAVE_STDLIB_H"] = "yes"
hdefs["_MK_HAVE_STDLIB_H"] = "yes"
mdefs["_MK_HAVE_UNISTD_H"] = "no"
hdefs["_MK_HAVE_UNISTD_H"] = nil
mdefs["_MK_HAVE_LIMITS_H"] = "no"
hdefs["_MK_HAVE_LIMITS_H"] = nil
mdefs["_MK_HAVE_FLOAT_H"] = "yes"
hdefs["_MK_HAVE_FLOAT_H"] = "yes"
hdefs["HAVE_PROGNAME"] = nil
mdefs["HAVE_MATH"] = "yes"
hdefs["HAVE_MATH"] = "yes"
mdefs["MATH_CFLAGS"] = ""
hdefs["MATH_CFLAGS"] = ""
mdefs["MATH_LIBS"] = "-lm"
hdefs["MATH_LIBS"] = "-lm"
mdefs["HAVE_MATH_C99"] = "yes"
hdefs["HAVE_MATH_C99"] = "yes"
mdefs["MATH_C99_CFLAGS"] = ""
hdefs["MATH_C99_CFLAGS"] = ""
mdefs["MATH_C99_LIBS"] = "-lm"
hdefs["MATH_C99_LIBS"] = "-lm"
hdefs["HAVE_GETPWUID"] = nil
hdefs["HAVE_GETUID"] = nil
hdefs["HAVE_STRSEP"] = nil
hdefs["HAVE_SNPRINTF"] = "yes"
hdefs["HAVE_VSNPRINTF"] = "yes"
mdefs["HAVE_VASPRINTF"] = "no"
hdefs["HAVE_VASPRINTF"] = nil
hdefs["_MK_HAVE_SIGNAL"] = "yes"
hdefs["_MK_HAVE_SETJMP"] = "yes"
hdefs["_MK_HAVE_STRTOLL"] = nil
hdefs["_MK_HAVE_STRTOLD"] = nil
hdefs["_MK_LITTLE_ENDIAN"] = "yes"
hdefs["_MK_BIG_ENDIAN"] = nil
hdefs["HAVE_DLFCN_H"] = nil
hdefs["HAVE_DLOPEN"] = nil
mdefs["HAVE_DLOPEN"] = "no"
hdefs["HAVE_DLOPEN"] = nil
mdefs["DSO_CFLAGS"] = ""
hdefs["DSO_CFLAGS"] = ""
mdefs["DSO_LIBS"] = ""
hdefs["DSO_LIBS"] = ""
hdefs["HAVE_MACH_O_DYLD_H"] = nil
hdefs["HAVE_DYLD"] = nil
hdefs["HAVE_DYLD_RETURN_ON_ERROR"] = nil
mdefs["DSO_CFLAGS"] = ""
hdefs["DSO_CFLAGS"] = ""
mdefs["DSO_LIBS"] = ""
hdefs["DSO_LIBS"] = ""
hdefs["HAVE_DL_H"] = nil
mdefs["HAVE_SHL_LOAD"] = "no"
hdefs["HAVE_SHL_LOAD"] = nil
hdefs["HAVE_SHL_LOAD"] = nil
hdefs["HAVE_GETTIMEOFDAY"] = nil
hdefs["HAVE_SELECT"] = nil
hdefs["HAVE_SETPROCTITLE"] = nil
hdefs["HAVE_SYSLOG"] = nil
hdefs["HAVE_SYSLOG_R"] = nil
hdefs["HAVE_VSYSLOG"] = nil
hdefs["HAVE_VSYSLOG_R"] = nil
hdefs["HAVE_GLOB"] = nil
hdefs["HAVE_GETOPT"] = nil
hdefs["HAVE_EXECVP"] = nil
mdefs["HAVE_CLOCK_GETTIME"] = "no"
hdefs["HAVE_CLOCK_GETTIME"] = nil
mdefs["HAVE_CLOCK_GETTIME"] = "no"
hdefs["HAVE_CLOCK_GETTIME"] = nil
hdefs["HAVE_CLOCK_GETTIME"] = nil
mdefs["HAVE_CLOCK_WIN32"] = "no"
hdefs["HAVE_CLOCK_WIN32"] = nil
hdefs["HAVE_CLOCK_WIN32"] = nil
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE"
mdefs["WNO_UNINITIALIZED"] = ""
hdefs["AG_DEBUG"] = "yes"
hdefs["AG_OBJDEBUG"] = nil
hdefs["AG_LEGACY"] = "yes"
hdefs["ENABLE_GUI"] = "yes"
mdefs["SUBDIR_gui"] = "gui"
mdefs["HAVE_SDL"] = "yes"
hdefs["HAVE_SDL"] = "yes"
mdefs["SDL_CFLAGS"] = "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main"
hdefs["SDL_CFLAGS"] = "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main"
mdefs["SDL_LIBS"] = "-L/usr/local/lib -lmingw32 -lSDLmain -lSDL -mwindows"
hdefs["SDL_LIBS"] = "-L/usr/local/lib -lmingw32 -lSDLmain -lSDL -mwindows"
mdefs["HAVE_LIBOPENGL32"] = "yes"
hdefs["HAVE_LIBOPENGL32"] = "yes"
mdefs["HAVE_OPENGL"] = "yes"
hdefs["HAVE_OPENGL"] = "yes"
mdefs["OPENGL_CFLAGS"] = ""
hdefs["OPENGL_CFLAGS"] = ""
mdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32"
hdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32"
mdefs["SDL_CFLAGS"] = "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main "
mdefs["HAVE_X11"] = "no"
hdefs["HAVE_X11"] = nil
hdefs["X11_CFLAGS"] = nil
hdefs["X11_LIBS"] = nil
hdefs["HAVE_X11"] = nil
mdefs["HAVE_GLX"] = "no"
hdefs["HAVE_GLX"] = nil
hdefs["GLX_CFLAGS"] = nil
hdefs["GLX_LIBS"] = nil
hdefs["HAVE_GLX"] = nil
mdefs["HAVE_WGL"] = "yes"
hdefs["HAVE_WGL"] = "yes"
mdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32 -lgdi32"
hdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32 -lgdi32"
mdefs["HAVE_FREETYPE"] = "yes"
hdefs["HAVE_FREETYPE"] = "yes"
mdefs["FREETYPE_CFLAGS"] = "-I/usr/local/include/freetype2 -I/usr/local/include"
hdefs["FREETYPE_CFLAGS"] = "-I/usr/local/include/freetype2 -I/usr/local/include"
mdefs["FREETYPE_LIBS"] = "-L/usr/local/lib -lfreetype"
hdefs["FREETYPE_LIBS"] = "-L/usr/local/lib -lfreetype"
hdefs["HAVE_JPEG"] = nil
hdefs["JPEG_CFLAGS"] = nil
hdefs["JPEG_LIBS"] = nil
hdefs["HAVE_JPEG"] = nil
hdefs["HAVE_PNG"] = nil
hdefs["PNG_CFLAGS"] = nil
hdefs["PNG_LIBS"] = nil
hdefs["HAVE_LIBPNG14"] = nil
hdefs["HAVE_PNG"] = nil
hdefs["AG_NETWORK"] = nil
hdefs["HAVE_GETADDRINFO"] = nil
hdefs["HAVE_DB4"] = nil
mdefs["DB4_CFLAGS"] = ""
mdefs["DB4_LIBS"] = ""
mdefs["HAVE_PTHREADS"] = "yes"
hdefs["HAVE_PTHREADS"] = "yes"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE "
mdefs["PTHREADS_CFLAGS"] = ""
mdefs["PTHREADS_LIBS"] = "-lpthread"
hdefs["PTHREADS_CFLAGS"] = ""
hdefs["PTHREADS_LIBS"] = "-lpthread"
mdefs["HAVE_PTHREADS_XOPEN"] = "yes"
hdefs["HAVE_PTHREADS_XOPEN"] = "yes"
mdefs["PTHREADS_XOPEN_CFLAGS"] = "-U_XOPEN_SOURCE -D_XOPEN_SOURCE=600"
mdefs["PTHREADS_XOPEN_LIBS"] = "-lpthread"
hdefs["HAVE_PTHREADS_XOPEN"] = "yes"
hdefs["PTHREADS_XOPEN_CFLAGS"] = "-U_XOPEN_SOURCE -D_XOPEN_SOURCE=600"
hdefs["PTHREADS_XOPEN_LIBS"] = "-lpthread"
mdefs["HAVE_PTHREAD_MUTEX_RECURSIVE"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE"] = "yes"
mdefs["HAVE_PTHREAD_MUTEX_RECURSIVE_NP"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE_NP"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE_NP"] = "yes"
hdefs["AG_THREADS"] = "yes"
hdefs["ASTRONOMICAL_UNITS"] = nil
hdefs["HISTORICAL_UNITS"] = "yes"
hdefs["ENABLE_MATH"] = "yes"
mdefs["SUBDIR_math"] = "math"
hdefs["HAVE_SSE"] = nil
hdefs["HAVE_SSE2"] = nil
hdefs["HAVE_SSE3"] = nil
hdefs["INLINE_SSE"] = nil
hdefs["INLINE_SSE2"] = nil
hdefs["INLINE_SSE3"] = nil
hdefs["HAVE_ALTIVEC"] = nil
hdefs["HAVE_ALTIVEC_H"] = nil
hdefs["INLINE_ALTIVEC"] = nil
hdefs["SINGLE_PRECISION"] = nil
hdefs["DOUBLE_PRECISION"] = "yes"
hdefs["QUAD_PRECISION"] = nil
hdefs["ENABLE_VG"] = "yes"
mdefs["SUBDIR_vg"] = "vg"
hdefs["ENABLE_RG"] = "yes"
mdefs["SUBDIR_rg"] = "rg"
hdefs["ENABLE_DEV"] = "yes"
mdefs["SUBDIR_dev"] = "dev"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE  -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE  -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include/agar"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include/agar"
hdefs["ENABLE_NLS"] = nil
mdefs["ENABLE_NLS"] = "no"
mdefs["HAVE_GETTEXT"] = "no"
hdefs["PREFIX"] = "/usr/local"
hdefs["LOCALEDIR"] = "/locale"
hdefs["MANDIR"] = "/usr/local/man"
hdefs["SHAREDIR"] = "/usr/local/share"
hdefs["DATADIR"] = "/usr/local/share"
hdefs["LIBDIR"] = "/usr/local/lib"
hdefs["SBINDIR"] = "/usr/local/sbin"
hdefs["INFODIR"] = "/usr/local/share/info"
hdefs["SYSCONFDIR"] = "/usr/local/etc"
hdefs["BINDIR"] = "/usr/local/bin"
hdefs["LIBEXECDIR"] = "/usr/local/libexec"
hdefs["LOCALSTATEDIR"] = "/usr/local/var"
mdefs["PACKAGE"] = "Agar"
hdefs["PACKAGE"] = "Agar"
mdefs["VERSION"] = "1.4.1"
hdefs["VERSION"] = "1.4.1"
mdefs["RELEASE"] = "Landscapes of Frozen Methane"
hdefs["RELEASE"] = "Landscapes of Frozen Methane"
mdefs["SHAREDIR"] = "${PREFIX}/share/agar"
hdefs["SHAREDIR"] = "/usr/local/share/agar"
mdefs["LOCALEDIR"] = "${PREFIX}/share/agar/locale"
hdefs["LOCALEDIR"] = "/usr/local/share/agar/locale"
mdefs["TTFDIR"] = "${PREFIX}/share/agar/fonts"
hdefs["TTFDIR"] = "/usr/local/share/agar/fonts"
mdefs["INCLDIR"] = "${PREFIX}/include/agar"
hdefs["INCLDIR"] = "/usr/local/include/agar"
mdefs["EXECSUFFIX"] = ".exe"
hdefs["EXECSUFFIX"] = ".exe"
mdefs["HAVE_CC_WARNINGS"] = "yes"
hdefs["HAVE_CC_WARNINGS"] = "yes"
mdefs["HAVE_GCC"] = "yes"
hdefs["HAVE_GCC"] = "yes"
mdefs["HAVE_IEEE754"] = "no"
hdefs["HAVE_IEEE754"] = nil
mdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
hdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
mdefs["HAVE_BOUNDED_ATTRIBUTE"] = "no"
hdefs["HAVE_BOUNDED_ATTRIBUTE"] = nil
mdefs["HAVE_CONST_ATTRIBUTE"] = "yes"
hdefs["HAVE_CONST_ATTRIBUTE"] = "yes"
mdefs["HAVE_DEPRECATED_ATTRIBUTE"] = "yes"
hdefs["HAVE_DEPRECATED_ATTRIBUTE"] = "yes"
mdefs["HAVE_FORMAT_ATTRIBUTE"] = "yes"
hdefs["HAVE_FORMAT_ATTRIBUTE"] = "yes"
mdefs["HAVE_NONNULL_ATTRIBUTE"] = "yes"
hdefs["HAVE_NONNULL_ATTRIBUTE"] = "yes"
mdefs["HAVE_NORETURN_ATTRIBUTE"] = "yes"
hdefs["HAVE_NORETURN_ATTRIBUTE"] = "yes"
mdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
hdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
mdefs["HAVE_PURE_ATTRIBUTE"] = "yes"
hdefs["HAVE_PURE_ATTRIBUTE"] = "yes"
mdefs["HAVE_WARN_UNUSED_RESULT_ATTRIBUTE"] = "yes"
hdefs["HAVE_WARN_UNUSED_RESULT_ATTRIBUTE"] = "yes"
hdefs["HAVE_LONG_DOUBLE"] = nil
hdefs["HAVE_LONG_LONG"] = nil
mdefs["HAVE_CYGWIN"] = "no"
hdefs["HAVE_CYGWIN"] = nil
mdefs["CC"] = "/mingw/bin/cc"
mdefs["CFLAGS"] = ""
mdefs["_MK_HAVE_SYS_TYPES_H"] = "yes"
hdefs["_MK_HAVE_SYS_TYPES_H"] = "yes"
mdefs["HAVE_64BIT"] = "no"
hdefs["HAVE_64BIT"] = nil
mdefs["_MK_HAVE_UNSIGNED_TYPEDEFS"] = "no"
hdefs["_MK_HAVE_UNSIGNED_TYPEDEFS"] = nil
mdefs["_MK_HAVE_STDLIB_H"] = "yes"
hdefs["_MK_HAVE_STDLIB_H"] = "yes"
mdefs["_MK_HAVE_UNISTD_H"] = "no"
hdefs["_MK_HAVE_UNISTD_H"] = nil
mdefs["_MK_HAVE_LIMITS_H"] = "no"
hdefs["_MK_HAVE_LIMITS_H"] = nil
mdefs["_MK_HAVE_FLOAT_H"] = "yes"
hdefs["_MK_HAVE_FLOAT_H"] = "yes"
hdefs["HAVE_PROGNAME"] = nil
mdefs["HAVE_MATH"] = "yes"
hdefs["HAVE_MATH"] = "yes"
mdefs["MATH_CFLAGS"] = ""
hdefs["MATH_CFLAGS"] = ""
mdefs["MATH_LIBS"] = "-lm"
hdefs["MATH_LIBS"] = "-lm"
mdefs["HAVE_MATH_C99"] = "yes"
hdefs["HAVE_MATH_C99"] = "yes"
mdefs["MATH_C99_CFLAGS"] = ""
hdefs["MATH_C99_CFLAGS"] = ""
mdefs["MATH_C99_LIBS"] = "-lm"
hdefs["MATH_C99_LIBS"] = "-lm"
hdefs["HAVE_GETPWUID"] = nil
hdefs["HAVE_GETUID"] = nil
hdefs["HAVE_STRSEP"] = nil
hdefs["HAVE_SNPRINTF"] = "yes"
hdefs["HAVE_VSNPRINTF"] = "yes"
mdefs["HAVE_VASPRINTF"] = "no"
hdefs["HAVE_VASPRINTF"] = nil
hdefs["_MK_HAVE_SIGNAL"] = "yes"
hdefs["_MK_HAVE_SETJMP"] = "yes"
hdefs["_MK_HAVE_STRTOLL"] = nil
hdefs["_MK_HAVE_STRTOLD"] = nil
hdefs["_MK_LITTLE_ENDIAN"] = "yes"
hdefs["_MK_BIG_ENDIAN"] = nil
hdefs["HAVE_DLFCN_H"] = nil
hdefs["HAVE_DLOPEN"] = nil
mdefs["HAVE_DLOPEN"] = "no"
hdefs["HAVE_DLOPEN"] = nil
mdefs["DSO_CFLAGS"] = ""
hdefs["DSO_CFLAGS"] = ""
mdefs["DSO_LIBS"] = ""
hdefs["DSO_LIBS"] = ""
hdefs["HAVE_MACH_O_DYLD_H"] = nil
hdefs["HAVE_DYLD"] = nil
hdefs["HAVE_DYLD_RETURN_ON_ERROR"] = nil
mdefs["DSO_CFLAGS"] = ""
hdefs["DSO_CFLAGS"] = ""
mdefs["DSO_LIBS"] = ""
hdefs["DSO_LIBS"] = ""
hdefs["HAVE_DL_H"] = nil
mdefs["HAVE_SHL_LOAD"] = "no"
hdefs["HAVE_SHL_LOAD"] = nil
hdefs["HAVE_SHL_LOAD"] = nil
hdefs["HAVE_GETTIMEOFDAY"] = nil
hdefs["HAVE_SELECT"] = nil
hdefs["HAVE_SETPROCTITLE"] = nil
hdefs["HAVE_SYSLOG"] = nil
hdefs["HAVE_SYSLOG_R"] = nil
hdefs["HAVE_VSYSLOG"] = nil
hdefs["HAVE_VSYSLOG_R"] = nil
hdefs["HAVE_GLOB"] = nil
hdefs["HAVE_GETOPT"] = nil
hdefs["HAVE_EXECVP"] = nil
mdefs["HAVE_CLOCK_GETTIME"] = "no"
hdefs["HAVE_CLOCK_GETTIME"] = nil
mdefs["HAVE_CLOCK_GETTIME"] = "no"
hdefs["HAVE_CLOCK_GETTIME"] = nil
hdefs["HAVE_CLOCK_GETTIME"] = nil
mdefs["HAVE_CLOCK_WIN32"] = "no"
hdefs["HAVE_CLOCK_WIN32"] = nil
hdefs["HAVE_CLOCK_WIN32"] = nil
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE"
mdefs["WNO_UNINITIALIZED"] = ""
hdefs["AG_DEBUG"] = "yes"
hdefs["AG_OBJDEBUG"] = nil
hdefs["AG_LEGACY"] = "yes"
hdefs["ENABLE_GUI"] = "yes"
mdefs["SUBDIR_gui"] = "gui"
mdefs["HAVE_SDL"] = "yes"
hdefs["HAVE_SDL"] = "yes"
mdefs["SDL_CFLAGS"] = "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main"
hdefs["SDL_CFLAGS"] = "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main"
mdefs["SDL_LIBS"] = "-L/usr/local/lib -lmingw32 -lSDLmain -lSDL -mwindows"
hdefs["SDL_LIBS"] = "-L/usr/local/lib -lmingw32 -lSDLmain -lSDL -mwindows"
mdefs["HAVE_LIBOPENGL32"] = "yes"
hdefs["HAVE_LIBOPENGL32"] = "yes"
mdefs["HAVE_OPENGL"] = "yes"
hdefs["HAVE_OPENGL"] = "yes"
mdefs["OPENGL_CFLAGS"] = ""
hdefs["OPENGL_CFLAGS"] = ""
mdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32"
hdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32"
mdefs["SDL_CFLAGS"] = "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main "
mdefs["HAVE_X11"] = "no"
hdefs["HAVE_X11"] = nil
hdefs["X11_CFLAGS"] = nil
hdefs["X11_LIBS"] = nil
hdefs["HAVE_X11"] = nil
mdefs["HAVE_GLX"] = "no"
hdefs["HAVE_GLX"] = nil
hdefs["GLX_CFLAGS"] = nil
hdefs["GLX_LIBS"] = nil
hdefs["HAVE_GLX"] = nil
mdefs["HAVE_WGL"] = "yes"
hdefs["HAVE_WGL"] = "yes"
mdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32 -lgdi32"
hdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32 -lgdi32"
mdefs["HAVE_FREETYPE"] = "yes"
hdefs["HAVE_FREETYPE"] = "yes"
mdefs["FREETYPE_CFLAGS"] = "-I/usr/local/include/freetype2 -I/usr/local/include"
hdefs["FREETYPE_CFLAGS"] = "-I/usr/local/include/freetype2 -I/usr/local/include"
mdefs["FREETYPE_LIBS"] = "-L/usr/local/lib -lfreetype"
hdefs["FREETYPE_LIBS"] = "-L/usr/local/lib -lfreetype"
hdefs["HAVE_JPEG"] = nil
hdefs["JPEG_CFLAGS"] = nil
hdefs["JPEG_LIBS"] = nil
hdefs["HAVE_JPEG"] = nil
hdefs["HAVE_PNG"] = nil
hdefs["PNG_CFLAGS"] = nil
hdefs["PNG_LIBS"] = nil
hdefs["HAVE_LIBPNG14"] = nil
hdefs["HAVE_PNG"] = nil
hdefs["AG_NETWORK"] = nil
hdefs["HAVE_GETADDRINFO"] = nil
hdefs["HAVE_DB4"] = nil
mdefs["DB4_CFLAGS"] = ""
mdefs["DB4_LIBS"] = ""
mdefs["HAVE_PTHREADS"] = "yes"
hdefs["HAVE_PTHREADS"] = "yes"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE "
mdefs["PTHREADS_CFLAGS"] = ""
mdefs["PTHREADS_LIBS"] = "-lpthread"
hdefs["PTHREADS_CFLAGS"] = ""
hdefs["PTHREADS_LIBS"] = "-lpthread"
mdefs["HAVE_PTHREADS_XOPEN"] = "yes"
hdefs["HAVE_PTHREADS_XOPEN"] = "yes"
mdefs["PTHREADS_XOPEN_CFLAGS"] = "-U_XOPEN_SOURCE -D_XOPEN_SOURCE=600"
mdefs["PTHREADS_XOPEN_LIBS"] = "-lpthread"
hdefs["HAVE_PTHREADS_XOPEN"] = "yes"
hdefs["PTHREADS_XOPEN_CFLAGS"] = "-U_XOPEN_SOURCE -D_XOPEN_SOURCE=600"
hdefs["PTHREADS_XOPEN_LIBS"] = "-lpthread"
mdefs["HAVE_PTHREAD_MUTEX_RECURSIVE"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE"] = "yes"
mdefs["HAVE_PTHREAD_MUTEX_RECURSIVE_NP"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE_NP"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE_NP"] = "yes"
hdefs["AG_THREADS"] = "yes"
hdefs["ASTRONOMICAL_UNITS"] = nil
hdefs["HISTORICAL_UNITS"] = "yes"
hdefs["ENABLE_MATH"] = "yes"
mdefs["SUBDIR_math"] = "math"
hdefs["HAVE_SSE"] = nil
hdefs["HAVE_SSE2"] = nil
hdefs["HAVE_SSE3"] = nil
hdefs["INLINE_SSE"] = nil
hdefs["INLINE_SSE2"] = nil
hdefs["INLINE_SSE3"] = nil
hdefs["HAVE_ALTIVEC"] = nil
hdefs["HAVE_ALTIVEC_H"] = nil
hdefs["INLINE_ALTIVEC"] = nil
hdefs["SINGLE_PRECISION"] = nil
hdefs["DOUBLE_PRECISION"] = "yes"
hdefs["QUAD_PRECISION"] = nil
hdefs["ENABLE_VG"] = "yes"
mdefs["SUBDIR_vg"] = "vg"
hdefs["ENABLE_RG"] = "yes"
mdefs["SUBDIR_rg"] = "rg"
hdefs["ENABLE_DEV"] = "yes"
mdefs["SUBDIR_dev"] = "dev"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE  -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE  -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include/agar"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include/agar"
hdefs["ENABLE_NLS"] = nil
mdefs["ENABLE_NLS"] = "no"
mdefs["HAVE_GETTEXT"] = "no"
hdefs["PREFIX"] = "/usr/local"
hdefs["LOCALEDIR"] = "/locale"
hdefs["MANDIR"] = "/usr/local/man"
hdefs["SHAREDIR"] = "/usr/local/share"
hdefs["DATADIR"] = "/usr/local/share"
hdefs["LIBDIR"] = "/usr/local/lib"
hdefs["SBINDIR"] = "/usr/local/sbin"
hdefs["INFODIR"] = "/usr/local/share/info"
hdefs["SYSCONFDIR"] = "/usr/local/etc"
hdefs["BINDIR"] = "/usr/local/bin"
hdefs["LIBEXECDIR"] = "/usr/local/libexec"
hdefs["LOCALSTATEDIR"] = "/usr/local/var"
mdefs["PACKAGE"] = "Agar"
hdefs["PACKAGE"] = "Agar"
mdefs["VERSION"] = "1.4.1"
hdefs["VERSION"] = "1.4.1"
mdefs["RELEASE"] = "Landscapes of Frozen Methane"
hdefs["RELEASE"] = "Landscapes of Frozen Methane"
mdefs["SHAREDIR"] = "${PREFIX}/share/agar"
hdefs["SHAREDIR"] = "/usr/local/share/agar"
mdefs["LOCALEDIR"] = "${PREFIX}/share/agar/locale"
hdefs["LOCALEDIR"] = "/usr/local/share/agar/locale"
mdefs["TTFDIR"] = "${PREFIX}/share/agar/fonts"
hdefs["TTFDIR"] = "/usr/local/share/agar/fonts"
mdefs["INCLDIR"] = "${PREFIX}/include/agar"
hdefs["INCLDIR"] = "/usr/local/include/agar"
mdefs["EXECSUFFIX"] = ".exe"
hdefs["EXECSUFFIX"] = ".exe"
mdefs["HAVE_CC_WARNINGS"] = "yes"
hdefs["HAVE_CC_WARNINGS"] = "yes"
mdefs["HAVE_GCC"] = "yes"
hdefs["HAVE_GCC"] = "yes"
mdefs["HAVE_IEEE754"] = "no"
hdefs["HAVE_IEEE754"] = nil
mdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
hdefs["HAVE_ALIGNED_ATTRIBUTE"] = "yes"
mdefs["HAVE_BOUNDED_ATTRIBUTE"] = "no"
hdefs["HAVE_BOUNDED_ATTRIBUTE"] = nil
mdefs["HAVE_CONST_ATTRIBUTE"] = "yes"
hdefs["HAVE_CONST_ATTRIBUTE"] = "yes"
mdefs["HAVE_DEPRECATED_ATTRIBUTE"] = "yes"
hdefs["HAVE_DEPRECATED_ATTRIBUTE"] = "yes"
mdefs["HAVE_FORMAT_ATTRIBUTE"] = "yes"
hdefs["HAVE_FORMAT_ATTRIBUTE"] = "yes"
mdefs["HAVE_NONNULL_ATTRIBUTE"] = "yes"
hdefs["HAVE_NONNULL_ATTRIBUTE"] = "yes"
mdefs["HAVE_NORETURN_ATTRIBUTE"] = "yes"
hdefs["HAVE_NORETURN_ATTRIBUTE"] = "yes"
mdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
hdefs["HAVE_PACKED_ATTRIBUTE"] = "yes"
mdefs["HAVE_PURE_ATTRIBUTE"] = "yes"
hdefs["HAVE_PURE_ATTRIBUTE"] = "yes"
mdefs["HAVE_WARN_UNUSED_RESULT_ATTRIBUTE"] = "yes"
hdefs["HAVE_WARN_UNUSED_RESULT_ATTRIBUTE"] = "yes"
hdefs["HAVE_LONG_DOUBLE"] = nil
hdefs["HAVE_LONG_LONG"] = nil
mdefs["HAVE_CYGWIN"] = "no"
hdefs["HAVE_CYGWIN"] = nil
mdefs["CC"] = "/mingw/bin/cc"
mdefs["CFLAGS"] = ""
mdefs["_MK_HAVE_SYS_TYPES_H"] = "yes"
hdefs["_MK_HAVE_SYS_TYPES_H"] = "yes"
mdefs["HAVE_64BIT"] = "no"
hdefs["HAVE_64BIT"] = nil
mdefs["_MK_HAVE_UNSIGNED_TYPEDEFS"] = "no"
hdefs["_MK_HAVE_UNSIGNED_TYPEDEFS"] = nil
mdefs["_MK_HAVE_STDLIB_H"] = "yes"
hdefs["_MK_HAVE_STDLIB_H"] = "yes"
mdefs["_MK_HAVE_UNISTD_H"] = "no"
hdefs["_MK_HAVE_UNISTD_H"] = nil
mdefs["_MK_HAVE_LIMITS_H"] = "no"
hdefs["_MK_HAVE_LIMITS_H"] = nil
mdefs["_MK_HAVE_FLOAT_H"] = "yes"
hdefs["_MK_HAVE_FLOAT_H"] = "yes"
hdefs["HAVE_PROGNAME"] = nil
mdefs["HAVE_MATH"] = "yes"
hdefs["HAVE_MATH"] = "yes"
mdefs["MATH_CFLAGS"] = ""
hdefs["MATH_CFLAGS"] = ""
mdefs["MATH_LIBS"] = "-lm"
hdefs["MATH_LIBS"] = "-lm"
mdefs["HAVE_MATH_C99"] = "yes"
hdefs["HAVE_MATH_C99"] = "yes"
mdefs["MATH_C99_CFLAGS"] = ""
hdefs["MATH_C99_CFLAGS"] = ""
mdefs["MATH_C99_LIBS"] = "-lm"
hdefs["MATH_C99_LIBS"] = "-lm"
hdefs["HAVE_GETPWUID"] = nil
hdefs["HAVE_GETUID"] = nil
hdefs["HAVE_STRSEP"] = nil
hdefs["HAVE_SNPRINTF"] = "yes"
hdefs["HAVE_VSNPRINTF"] = "yes"
mdefs["HAVE_VASPRINTF"] = "no"
hdefs["HAVE_VASPRINTF"] = nil
hdefs["_MK_HAVE_SIGNAL"] = "yes"
hdefs["_MK_HAVE_SETJMP"] = "yes"
hdefs["_MK_HAVE_STRTOLL"] = nil
hdefs["_MK_HAVE_STRTOLD"] = nil
hdefs["_MK_LITTLE_ENDIAN"] = "yes"
hdefs["_MK_BIG_ENDIAN"] = nil
hdefs["HAVE_DLFCN_H"] = nil
hdefs["HAVE_DLOPEN"] = nil
mdefs["HAVE_DLOPEN"] = "no"
hdefs["HAVE_DLOPEN"] = nil
mdefs["DSO_CFLAGS"] = ""
hdefs["DSO_CFLAGS"] = ""
mdefs["DSO_LIBS"] = ""
hdefs["DSO_LIBS"] = ""
hdefs["HAVE_MACH_O_DYLD_H"] = nil
hdefs["HAVE_DYLD"] = nil
hdefs["HAVE_DYLD_RETURN_ON_ERROR"] = nil
mdefs["DSO_CFLAGS"] = ""
hdefs["DSO_CFLAGS"] = ""
mdefs["DSO_LIBS"] = ""
hdefs["DSO_LIBS"] = ""
hdefs["HAVE_DL_H"] = nil
mdefs["HAVE_SHL_LOAD"] = "no"
hdefs["HAVE_SHL_LOAD"] = nil
hdefs["HAVE_SHL_LOAD"] = nil
hdefs["HAVE_GETTIMEOFDAY"] = nil
hdefs["HAVE_SELECT"] = nil
hdefs["HAVE_SETPROCTITLE"] = nil
hdefs["HAVE_SYSLOG"] = nil
hdefs["HAVE_SYSLOG_R"] = nil
hdefs["HAVE_VSYSLOG"] = nil
hdefs["HAVE_VSYSLOG_R"] = nil
hdefs["HAVE_GLOB"] = nil
hdefs["HAVE_GETOPT"] = nil
hdefs["HAVE_EXECVP"] = nil
mdefs["HAVE_CLOCK_GETTIME"] = "no"
hdefs["HAVE_CLOCK_GETTIME"] = nil
mdefs["HAVE_CLOCK_GETTIME"] = "no"
hdefs["HAVE_CLOCK_GETTIME"] = nil
hdefs["HAVE_CLOCK_GETTIME"] = nil
mdefs["HAVE_CLOCK_WIN32"] = "no"
hdefs["HAVE_CLOCK_WIN32"] = nil
hdefs["HAVE_CLOCK_WIN32"] = nil
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE"
mdefs["WNO_UNINITIALIZED"] = ""
hdefs["AG_DEBUG"] = "yes"
hdefs["AG_OBJDEBUG"] = nil
hdefs["AG_LEGACY"] = "yes"
hdefs["ENABLE_GUI"] = "yes"
mdefs["SUBDIR_gui"] = "gui"
mdefs["HAVE_SDL"] = "yes"
hdefs["HAVE_SDL"] = "yes"
mdefs["SDL_CFLAGS"] = "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main"
hdefs["SDL_CFLAGS"] = "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main"
mdefs["SDL_LIBS"] = "-L/usr/local/lib -lmingw32 -lSDLmain -lSDL -mwindows"
hdefs["SDL_LIBS"] = "-L/usr/local/lib -lmingw32 -lSDLmain -lSDL -mwindows"
mdefs["HAVE_LIBOPENGL32"] = "yes"
hdefs["HAVE_LIBOPENGL32"] = "yes"
mdefs["HAVE_OPENGL"] = "yes"
hdefs["HAVE_OPENGL"] = "yes"
mdefs["OPENGL_CFLAGS"] = ""
hdefs["OPENGL_CFLAGS"] = ""
mdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32"
hdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32"
mdefs["SDL_CFLAGS"] = "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main "
mdefs["HAVE_X11"] = "no"
hdefs["HAVE_X11"] = nil
hdefs["X11_CFLAGS"] = nil
hdefs["X11_LIBS"] = nil
hdefs["HAVE_X11"] = nil
mdefs["HAVE_GLX"] = "no"
hdefs["HAVE_GLX"] = nil
hdefs["GLX_CFLAGS"] = nil
hdefs["GLX_LIBS"] = nil
hdefs["HAVE_GLX"] = nil
mdefs["HAVE_WGL"] = "yes"
hdefs["HAVE_WGL"] = "yes"
mdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32 -lgdi32"
hdefs["OPENGL_LIBS"] = " -L/usr/local/lib -lopengl32 -lgdi32"
mdefs["HAVE_FREETYPE"] = "yes"
hdefs["HAVE_FREETYPE"] = "yes"
mdefs["FREETYPE_CFLAGS"] = "-I/usr/local/include/freetype2 -I/usr/local/include"
hdefs["FREETYPE_CFLAGS"] = "-I/usr/local/include/freetype2 -I/usr/local/include"
mdefs["FREETYPE_LIBS"] = "-L/usr/local/lib -lfreetype"
hdefs["FREETYPE_LIBS"] = "-L/usr/local/lib -lfreetype"
hdefs["HAVE_JPEG"] = nil
hdefs["JPEG_CFLAGS"] = nil
hdefs["JPEG_LIBS"] = nil
hdefs["HAVE_JPEG"] = nil
hdefs["HAVE_PNG"] = nil
hdefs["PNG_CFLAGS"] = nil
hdefs["PNG_LIBS"] = nil
hdefs["HAVE_LIBPNG14"] = nil
hdefs["HAVE_PNG"] = nil
hdefs["AG_NETWORK"] = nil
hdefs["HAVE_GETADDRINFO"] = nil
hdefs["HAVE_DB4"] = nil
mdefs["DB4_CFLAGS"] = ""
mdefs["DB4_LIBS"] = ""
mdefs["HAVE_PTHREADS"] = "yes"
hdefs["HAVE_PTHREADS"] = "yes"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE "
mdefs["PTHREADS_CFLAGS"] = ""
mdefs["PTHREADS_LIBS"] = "-lpthread"
hdefs["PTHREADS_CFLAGS"] = ""
hdefs["PTHREADS_LIBS"] = "-lpthread"
mdefs["HAVE_PTHREADS_XOPEN"] = "yes"
hdefs["HAVE_PTHREADS_XOPEN"] = "yes"
mdefs["PTHREADS_XOPEN_CFLAGS"] = "-U_XOPEN_SOURCE -D_XOPEN_SOURCE=600"
mdefs["PTHREADS_XOPEN_LIBS"] = "-lpthread"
hdefs["HAVE_PTHREADS_XOPEN"] = "yes"
hdefs["PTHREADS_XOPEN_CFLAGS"] = "-U_XOPEN_SOURCE -D_XOPEN_SOURCE=600"
hdefs["PTHREADS_XOPEN_LIBS"] = "-lpthread"
mdefs["HAVE_PTHREAD_MUTEX_RECURSIVE"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE"] = "yes"
mdefs["HAVE_PTHREAD_MUTEX_RECURSIVE_NP"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE_NP"] = "yes"
hdefs["HAVE_PTHREAD_MUTEX_RECURSIVE_NP"] = "yes"
hdefs["AG_THREADS"] = "yes"
hdefs["ASTRONOMICAL_UNITS"] = nil
hdefs["HISTORICAL_UNITS"] = "yes"
hdefs["ENABLE_MATH"] = "yes"
mdefs["SUBDIR_math"] = "math"
hdefs["HAVE_SSE"] = nil
hdefs["HAVE_SSE2"] = nil
hdefs["HAVE_SSE3"] = nil
hdefs["INLINE_SSE"] = nil
hdefs["INLINE_SSE2"] = nil
hdefs["INLINE_SSE3"] = nil
hdefs["HAVE_ALTIVEC"] = nil
hdefs["HAVE_ALTIVEC_H"] = nil
hdefs["INLINE_ALTIVEC"] = nil
hdefs["SINGLE_PRECISION"] = nil
hdefs["DOUBLE_PRECISION"] = "yes"
hdefs["QUAD_PRECISION"] = nil
hdefs["ENABLE_VG"] = "yes"
mdefs["SUBDIR_vg"] = "vg"
hdefs["ENABLE_RG"] = "yes"
mdefs["SUBDIR_rg"] = "rg"
hdefs["ENABLE_DEV"] = "yes"
mdefs["SUBDIR_dev"] = "dev"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE  -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include"
mdefs["CFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE  -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include/agar"
mdefs["CXXFLAGS"] = " -D_AGAR_INTERNAL -D_BSD_SOURCE -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include -I/h/jkt/svn/trunk/moteur/libs/agar-1.4.1/include/agar"
